#!/usr/bin/env node

try {

	var nodeunit = require('nodeunit')
	  , assertExtras = require('./assert-extras')
    ;

} catch (e) {
	console.log("Cannot find necessary modules.");
	console.log("You must first install the necessary modules by doing:");
	console.log("");
	console.log("    npm install -dev");
	console.log("");
	process.exit();
}

process.chdir(__dirname);

nodeunit.assert = assertExtras;
nodeunit.reporters.default.run(['tests.js']);
